### ISSUE TITLE
Error: com.facebook.jni.CppException: Cannot read property '__workletHash'

### ISSUE THREAD

**Issue by JCYDigitalinnov** [backpackapp-io/react-native-toast#17]
I experience this error in rare case only. This is happens on both low-end and high-end devices when I tried to hold the toast and tried it to drag, then it crashes (native crash)

I currently using:
"@backpackapp-io/react-native-toast": "^0.9.0",
"react-native": "0.72.4",

```
com.facebook.jni.CppException: Cannot read property '__workletHash' of undefined TypeError: Cannot read property '__workletHash' of undefined at runOnJS (JavaScript:1:260) at anonymous (JavaScript:1:153) at apply (native) at runWorklet (JavaScript:1:207) at anonymous (JavaScript:1:886) at handleAndFlushAnimationFrame (JavaScript:1:147) at com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent(Native Method) at com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent(EventHandler.java:25) at com.swmansion.gesturehandler.react.RNGestureHandlerStateChangeEvent.dispatch(RNGestureHandlerStateChangeEvent.kt:42) at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:325) at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:308) at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116) at com.swmansion.gesturehandler.ReactContextExtensionsKt.dispatchEvent(ReactContextExtensions.kt:9) at com.swmansion.gesturehandler.react.RNGestureHandlerModule.sendEventForDirectEvent(RNGestureHandlerModule.kt:638) at com.swmansion.gesturehandler.react.RNGestureHandlerModule.sendEventForReanimated(RNGestureHandlerModule.kt:624) at com.swmansion.gesturehandler.react.RNGestureHandlerModule.onStateChange(RNGestureHandlerModule.kt:576) at com.swmansion.gesturehandler.react.RNGestureHandlerModule.access$onStateChange(RNGestureHandlerModule.kt:38) at com.swmansion.gesturehandler.react.RNGestureHandlerModule$eventListener$1.onStateChange(RNGestureHandlerModule.kt:346) at com.swmansion.gesturehandler.core.GestureHandler.dispatchStateChange(GestureHandler.kt:84) at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.onHandlerStateChange(GestureHandlerOrchestrator.kt:157) at com.swmansion.gesturehandler.core.GestureHandler.moveToState(GestureHandler.kt:551) at com.swmansion.gesturehandler.core.GestureHandler.end(GestureHandler.kt:666) at com.swmansion.gesturehandler.core.FlingGestureHandler.activate(FlingGestureHandler.kt:60) at com.swmansion.gesturehandler.core.GestureHandler.activate(GestureHandler.kt:650) at com.swmansion.gesturehandler.core.FlingGestureHandler.tryEndFling(FlingGestureHandler.kt:52) at com.swmansion.gesturehandler.core.FlingGestureHandler.onHandle(FlingGestureHandler.kt:75) at com.swmansion.gesturehandler.core.GestureHandler.handle(GestureHandler.kt:374) at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.deliverEventToGestureHandler(GestureHandlerOrchestrator.kt:276) at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.deliverEventToGestureHandlers(GestureHandlerOrchestrator.kt:231) at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.kt:45) at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.kt:97) at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.kt:35) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814) at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:571) at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899) at android.app.Activity.dispatchTouchEvent(Activity.java:4409) at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69) at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:529) at android.view.View.dispatchPointerEvent(View.java:15331) at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7009) at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6785) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6204) at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6261) at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6227) at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6392) at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6235) at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6449) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6208) at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6261) at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6227) at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6235) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6208) at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9373) at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9324) at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9292) at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9512) at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:298) at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method) at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:270) at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9458) at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9603) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459) at android.view.Choreographer.doCallbacks(Choreographer.java:1089) at android.view.Choreographer.doFrame(Choreographer.java:995) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:211) at android.os.Looper.loop(Looper.java:300) at android.app.ActivityThread.main(ActivityThread.java:8294) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by JCYDigitalinnov** [comment]
Duplicated #13 

Sorry about that
